# Generated by Django 3.2.9 on 2021-11-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20211102_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
