# Generated by Django 3.2.9 on 2021-11-02 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_auto_20211102_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='watchlist.platform'),
        ),
    ]
