# Generated by Django 3.2.9 on 2021-11-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_auto_20211102_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.media'),
        ),
    ]
